# Generated by Django 3.0.5 on 2020-05-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
