# Generated by Django 3.0.5 on 2020-04-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel_Prioridad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_prioridad', models.CharField(max_length=15)),
            ],
        ),
    ]
