# Generated by Django 3.0.5 on 2020-04-20 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='nivel_prioridad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoAPP.Nivel_Prioridad'),
        ),
    ]
