# Generated by Django 3.0.5 on 2020-04-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='sexo',
            field=models.CharField(default='Hombre', max_length=15),
            preserve_default=False,
        ),
    ]
