# Generated by Django 3.0.5 on 2020-04-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoAPP', '0002_auto_20200424_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='localizacion',
            field=models.CharField(max_length=50),
        ),
    ]
