# Generated by Django 3.0.5 on 2020-04-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='contraseña',
            field=models.CharField(default=1234567890, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estado',
            name='estado',
            field=models.CharField(default='Abierta', max_length=20),
        ),
    ]
